### ISSUE TITLE
Doesn't work with Blueprints

### ISSUE THREAD

**Issue by luckydonald** [cenkalti/github-flask#49]
```py
blueprint = Blueprint('oauth', __name__)
# setup github-flask
github = GitHub(blueprint)
```
results in
```python
Traceback (most recent call last):
...
  File "/Users/luckydonald/code/more_code/code/yes_code/github_oauth.py", line 14, in <module>
    github = GitHub(blueprint)
  File "/Users/luckydonald/code/virtualenv3.6.venv/lib/python3.6/site-packages/flask_github.py", line 81, in __init__
    self.init_app(self.app)
  File "/Users/luckydonald/code/virtualenv3.6.venv/lib/python3.6/site-packages/flask_github.py", line 86, in init_app
    self.client_id = app.config['GITHUB_CLIENT_ID']
AttributeError: 'Blueprint' object has no attribute 'config'
```

**Comment by luckydonald** [comment]
```py
# set up flask
blueprint = Blueprint('oauth', __name__)
blueprint.config = {
    'GITHUB_CLIENT_ID': GITHUB_CLIENT_ID,
    'GITHUB_CLIENT_SECRET': GITHUB_CLIENT_SECRET,
}
```
seems to fix this.
